# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minutia.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minutia.proto',
  package='',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rminutia.proto\"\xb1\x01\n\tMinutiapb\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x11\n\tdirection\x18\x03 \x01(\x05\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12$\n\x04type\x18\x05 \x01(\x0e\x32\x16.Minutiapb.MinutiaType\"A\n\x0bMinutiaType\x12\x15\n\x11MINUTIA_UNDEFINED\x10\x00\x12\n\n\x06\x45NDING\x10\x01\x12\x0f\n\x0b\x42IFURCATION\x10\x02\x42\x02H\x03\x62\x06proto3'
)



_MINUTIAPB_MINUTIATYPE = _descriptor.EnumDescriptor(
  name='MinutiaType',
  full_name='Minutiapb.MinutiaType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MINUTIA_UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENDING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIFURCATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=130,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_MINUTIAPB_MINUTIATYPE)


_MINUTIAPB = _descriptor.Descriptor(
  name='Minutiapb',
  full_name='Minutiapb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Minutiapb.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Minutiapb.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='Minutiapb.direction', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='Minutiapb.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='Minutiapb.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MINUTIAPB_MINUTIATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=195,
)

_MINUTIAPB.fields_by_name['type'].enum_type = _MINUTIAPB_MINUTIATYPE
_MINUTIAPB_MINUTIATYPE.containing_type = _MINUTIAPB
DESCRIPTOR.message_types_by_name['Minutiapb'] = _MINUTIAPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Minutiapb = _reflection.GeneratedProtocolMessageType('Minutiapb', (_message.Message,), {
  'DESCRIPTOR' : _MINUTIAPB,
  '__module__' : 'minutia_pb2'
  # @@protoc_insertion_point(class_scope:Minutiapb)
  })
_sym_db.RegisterMessage(Minutiapb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
